
development:
  adapter: postgresql
  encoding: unicode
  database: skysong_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: skysong_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: skysong_production
  pool: 5

